image: debian:buster

stages:
  - test
  - build

styling test:
  stage: test
  image: python:3.7
  script:
    - pip install --no-cache-dir -r requirements/dev.txt
    - mypy src/cyberfusion/RabbitMQConsumer/ --junit-xml report-mypy.xml
    - flake8 src/cyberfusion/RabbitMQConsumer/ --tee --output-file flake8.txt; exit_code=$?; flake8_junit flake8.txt report-flake8.xml; exit_code=$?; flake8_junit flake8.txt report-flake8.xml
    - if [ $exit_code -ne 0 ]; then exit 1; fi;
    - isort -c .
    - black --check .
  artifacts:
    reports:
      junit: report-*.xml

build test:
  stage: build
  script:
    - apt update
    - apt --no-install-recommends -y install apt-transport-https ca-certificates build-essential devscripts equivs gnupg lintian
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - mk-build-deps -i -t 'apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
    - dpkg-buildpackage -us -uc
    - lintian --dont-check-part=manpages ../*.changes

build:
  stage: build
  only:
    - master
  script:
    - apt update
    - apt --no-install-recommends -y install apt-transport-https ca-certificates build-essential devscripts equivs gnupg
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - mk-build-deps -i -t 'apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
    - dpkg-buildpackage -us -uc
    - mkdir publish
    - cp ../*.deb publish/
  artifacts:
    paths:
      - publish/*.deb
    expire_in: 1 week
