include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

unit test and feature test:
  stage: test
  image: python:3.11
  services:
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/3163#note_63471739
    - name: rabbitmq:3.13.6-management
      alias: rabbitmq
  variables:
    RABBITMQ_DEFAULT_USER: test
    RABBITMQ_DEFAULT_PASS: 'knvPSBPLkJSwTdMn6F4kkQkB'
    RABBITMQ_DEFAULT_VHOST: ci-test
  script:
    - !reference [.add repositories, script]
    - pip install --no-cache-dir -r requirements/test.txt
    - unlink rabbitmq.yml
    - ln -s rabbitmq.ci.yml rabbitmq.yml
    - pip install .
    - PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest -n 10 tests/RabbitMQConsumer/ -vvv --cov-branch --cov=cyberfusion.RabbitMQConsumer --cov-config=.coveragerc --cov-fail-under=1 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml
