include:
  - project: 'cyberfusion/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: cluster

stages:
  - test
  - build
  - publish

unit test:
  stage: test
  image: python:3.9
  services:
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/3163#note_63471739
    - name: rabbitmq:3.9.13-management
      alias: rabbitmq
  variables:
    RABBITMQ_DEFAULT_USER: test
    RABBITMQ_DEFAULT_PASS: 'knvPSBPLkJSwTdMn6F4kkQkB'
    RABBITMQ_DEFAULT_VHOST: ci-test
  script:
    - !reference [.add repositories, script]
    - apt -y install python-cyberfusion-common python3-sdnotify python3-yaml python3-systemd python-cyberfusion-cluster-rabbitmq-consumer python3-pika
    - pip install --no-cache-dir -r requirements/test.txt
    - RABBITMQ_PASSWORD='knvPSBPLkJSwTdMn6F4kkQkB' RABBITMQ_USERNAME=test RABBITMQ_VIRTUAL_HOST_NAME=ci-test RABBITMQ_HOST=rabbitmq PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest tests/unit_tests/RabbitMQConsumer/ -vvv --cov-branch --cov=cyberfusion.RabbitMQConsumer --cov-config=.coveragerc --cov-fail-under=10 --junitxml=report-pytest.xml
    - RABBITMQ_PASSWORD='knvPSBPLkJSwTdMn6F4kkQkB' RABBITMQ_USERNAME=test RABBITMQ_VIRTUAL_HOST_NAME=ci-test RABBITMQ_HOST=rabbitmq PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest tests/unit_tests/RabbitMQHandlers/ -vvv --cov-branch --cov=cyberfusion.RabbitMQHandlers --cov-config=.coveragerc --cov-fail-under=100 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml
