image: debian:buster

stages:
  - test
  - build

styling test:
  stage: test
  image: python:3.7
  script:
    - pip install --no-cache-dir -r requirements/dev.txt
    - mypy . --junit-xml report-mypy.xml
    - flake8 . --tee --output-file flake8.txt; exit_code=$?; flake8_junit flake8.txt report-flake8.xml
    - if [ $exit_code -ne 0 ]; then exit 1; fi;
    - isort -c .
    - black --check .
  artifacts:
    reports:
      junit: report-*.xml

unit test:
  stage: test
  image: python:3.7
  services:
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/3163#note_63471739
    - name: rabbitmq:3.9.13-management
      alias: rabbitmq
  variables:
    RABBITMQ_DEFAULT_USER: test
    RABBITMQ_DEFAULT_PASS: 'knvPSBPLkJSwTdMn6F4kkQkB'
    RABBITMQ_DEFAULT_VHOST: test
  script:
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - apt -y install python-cyberfusion-common python3-sdnotify python3-yaml python3-systemd
    - pip install --no-cache-dir -r requirements/test.txt
    - cp $CI_PROJECT_DIR/rabbitmq.yml /etc/cyberfusion/rabbitmq.yml
    - RABBITMQ_CONSUMER_CONFIG_FILE_PATH=/etc/cyberfusion/rabbitmq.yml PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest -vvv --cov-branch --cov=cyberfusion.RabbitMQConsumer --cov-config=.coveragerc --cov-fail-under=5 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml

build test:
  stage: test
  script:
    - apt update
    - apt --no-install-recommends -y install apt-transport-https ca-certificates build-essential devscripts equivs gnupg lintian
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - mk-build-deps -i -t 'apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
    - dpkg-buildpackage -us -uc
    - dpkg-genchanges > ../pkg.changes
    - lintian --dont-check-part=manpages ../pkg.changes

build:
  stage: build
  only:
    - master
  script:
    - apt update
    - apt --no-install-recommends -y install apt-transport-https ca-certificates build-essential devscripts equivs gnupg
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - mk-build-deps -i -t 'apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
    - dpkg-buildpackage -us -uc
    - mkdir publish
    - cp ../*.deb publish/
  artifacts:
    paths:
      - publish/*.deb
    expire_in: 1 week
