version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.13.6-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=C4P4BZFcaBUYk2PvVyZU7CV3
      - RABBITMQ_DEFAULT_VHOST=test
