[tool.isort]
profile = "black"
line_length = 79
skip = ["migrations"]
known_first_party = ["cyberfusion", "bin", "src", "migrations"]
default_section = "THIRDPARTY"

[tool.black]
line-length = 79
target-version = ["py37"]
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | venv
  )/
)
'''
